Repository antlilja/plusplus-os, pull requests merged in 2021-05, with the labels that each got.

#48 Memory refactor
  kernel/CMakeLists.txt
  kernel/include/memory.h
  kernel/include/memory/entry_pool.h
  kernel/include/memory/frame_allocator.h
  kernel/src/main.c
  kernel/src/memory.c
  kernel/src/memory/entry_pool.c
  kernel/src/memory/frame_allocator.c
Labels: refactor

#51 Paging improvements
  kernel/include/memory/paging.h
  kernel/src/memory/entry_pool.c
  kernel/src/memory/paging.c
  kernel/src/rendering.c
Labels: new feature

#52 PCI-Express device enumeration and config space
  CMakeLists.txt
  kernel/CMakeLists.txt
  kernel/include/acpi.h
  kernel/include/pci.h
  kernel/src/acpi.c
  kernel/src/main.c
  kernel/src/pci.c
Labels: new feature, refactor

#58 Address spaces
  kernel/include/memory/paging.h
  kernel/src/acpi.c
  kernel/src/apic.c
  kernel/src/memory.c
  kernel/src/memory/paging.c
  kernel/src/pci.c
  kernel/src/rendering.c
Labels: critical, new feature, refactor

#59 Interrupts improvement
  kernel/include/idt.h
  kernel/src/gdt.c
  kernel/src/idt.c
Labels: refactor

#61 Usermode prep/fixes
  kernel/include/gdt.h
  kernel/src/gdt.c
Labels: critical

#63 Added syscall support
  kernel/CMakeLists.txt
  kernel/include/syscalls.h
  kernel/src/main.c
  kernel/src/syscalls.c
Labels: new feature

#62 Slab allocator
  kernel/CMakeLists.txt
  kernel/include/memory.h
  kernel/include/memory/slab_allocator.h
  kernel/src/acpi.c
  kernel/src/memory.c
  kernel/src/memory/slab_allocator.c
  kernel/src/pci.c
Labels: new feature

#71 AHCI setup
  kernel/CMakeLists.txt
  kernel/include/ahci.h
  kernel/include/ahci/fis.h
  kernel/include/ahci/hba.h
  kernel/src/ahci.c
  kernel/src/main.c
Labels: new feature

#72 Added AHCI read_write_sectors function
  kernel/include/ahci.h
  kernel/src/ahci.c
Labels: new feature

#73 Add basic application target and terminal example
  CMakeLists.txt
  apps/CMakeLists.txt
  apps/linker.ld
  apps/terminal/CMakeLists.txt
  apps/terminal/src/main.c
Labels: new feature
